### ISSUE TITLE
Add CRITICAL/FATAL entry to log table

### ISSUE THREAD

**Issue by marcosschroh** [dscovr/loggify#3]
Goal: Add Critical/Fatal level in log table

Depending the language can we found as `critical` (Python) or `fatal` (Java). Is the highest value in numeric order. 

**Fatal**: Any error that is forcing a shutdown of the service or application to prevent data loss (or further data loss). I reserve these only for the most heinous errors and situations where there is guaranteed to have been data corruption or loss.

**Comment by Woile** [comment]
I don't know if we should include them for now, I'd use the most common ones. Have you used critical/fatal?
I'd provide the minimal information for logging, otherwise we'd be missing [TRACE](https://softwareengineering.stackexchange.com/questions/279690/why-does-the-trace-level-exist-and-when-should-i-use-it-rather-than-debug) as well

**Comment by marcosschroh** [comment]
There are only 5/6 levels that all languages recognize, why would the table be incomplete?. Let's add TRACE as well.

**Comment by Woile** [comment]
Because even if they exist, they are not usually used. I would avoid adding "cognitive load", we want to give enough information for people to use logs, not teach them everything, for that they can ready the already many many resources that exist about logging.

I have never used **TRACE**.

1. Why would I recommend to use it as the FIRST item in the list of logs?
2. Would you want people to start sending TRACE (or CRITICAL/FATAL) to your PRs?

**Comment by marcosschroh** [comment]
I think is only a table that is missing only 1/2 rows describing 1/2 logging levels that languages describes in their documentation, that is it.  I do not think that 1/2 rows is adding `cognitive load`.

**Comment by Woile** [comment]
The questions remains, even if it doesn't add "cognitive load", I think we'd be **teaching logging wrong**.
Beginners would start using those log levels, and they should be used only a small amount of times. I think those extra 2 are for special cases, and if you feel like using them, you'd have to research.
Just because they exist doesn't mean we should include them.

If we are going to add them all, we should follow the [Syslog Protocol RFC](https://tools.ietf.org/html/rfc5424#section-6.2.1) as well, which is the one used by [winston](https://github.com/winstonjs/winston) which we would eventually include.

```
 0       Emergency: system is unusable
1       Alert: action must be taken immediately
2       Critical: critical conditions
3       Error: error conditions
4       Warning: warning conditions
5       Notice: normal but significant condition
6       Informational: informational messages
7       Debug: debug-level messages
```

**Comment by marcosschroh** [comment]
Clearly, this discussion shows that we need to refine the goal about how this application can help people to understand/use logging. 

I do not think TRACE and CRITICAL are special cases as languages like `Python`, `Javascript` and `Java` mention them.

> Why would I recommend to use it as the FIRST item in the list of logs?

Is not a recommendation, is a summary of the levels. If I recall correctly,  I think we said that the recommendation will come later with a search form or wizard

> Would you want people to start sending TRACE (or CRITICAL/FATAL) to your PRs?

I have not idea. Depends what people have to do in their applications. For some reason those levels are there. I guess the power of this application will come later with the "recommendation engine" and not with the information list on a table.

**Comment by marcosschroh** [comment]
Anyway, for me is fine. Let's close this and we can re open later if it is necessary.
